name: Certora Prover Workflow

on:
  pull_request:
    branches:
      - certora
  push:
    branches:
      - certora

env:
  FOUNDRY_PROFILE: ci
  # Add your configurations as lines where each line is a separate configuration.
  # You can specify additional options for each configuration by adding them after the configuration.
  CONFIGS: |
    certora/conf/getAmountsTest.conf
    certora/conf/LendingPoolManager.conf
    certora/conf/MarginHook.conf
    certora/conf/PairPoolManager.conf
    certora/conf/PairPoolManagerCurrencyDeltas.conf


jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # installation steps 
      - name: Install dependencies
        run: yarn install

      # (Optional) Run Certora munge script
      - name: Certora munge
        run: sh ./certora/scripts/Patch.sh

      # Run Certora Prover
      - uses: Certora/certora-run-action@v1
        with:
          use-beta: true
          configurations: ${{ env.CONFIGS }}
          solc-versions: 0.8.26
          solc-remove-version-prefix: "0."
          job-name: "Verified Rules"
          certora-key: ${{ secrets.CERTORAKEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}